name: New EvtxECmd Map Request
description: Request for an EvtxECmd Map to be made for a currently unmapped event ID.
title: "[New Map Request]: Channel/Provider:ID"
labels: ["new map request", "needs triage"]
assignees:
  - AndrewRathbun
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Map request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: provider
    attributes:
      label: Provider
      description: Please provide the Provider of the event ID of interest.
      placeholder: ex. Service Control Manager
    validations:
      required: true
  - type: input
    id: channel
    attributes:
      label: Channel
      description: Please provide the Channel of the event ID of interest.
      placeholder: ex. System
    validations:
      required: true
  - type: input
    id: event-id
    attributes:
      label: Event ID
      description: Please provide the Event ID of interest.
      placeholder: ex. 7045
    validations:
      required: true
  - type: checkboxes
    id: existing-map
    attributes:
      label: Is there an existing Map for this Event ID?
      description: Please search to see if there is a pre-existing Map for this event. https://github.com/AndrewRathbun/evtx/tree/master/evtx/Maps
      options:
        - label: I have searched the existing Maps, and one does not exist already
          required: true
  - type: checkboxes
    id: existing-provider-csv
    attributes:
      label: Is there an existing CSV for this specific Event Log Provider?
      description: Please search to see if a pre-existing CSV exists for this Provider. https://github.com/nasbench/EVTX-ETW-Resources/tree/main/ETWProvidersCSVs
      options:
        - label: I have searched the existing Provider CSVs from the EVTX-ETW-Resources repo
          required: false
  - type: input
    id: existing-provider-csv-link
    attributes:
      label: Provider CSV Link
      description: Please provide a link to the Provider CSV from the EVTX-ETW Resources repo, if one exists.
      placeholder: ex. https://github.com/nasbench/EVTX-ETW-Resources/blob/main/ETWProvidersCSVs/Internal/Application%20Error.csv
    validations:
      required: false
  - type: textarea
    id: example-event-data
    attributes:
      label: Example Event Data
      description: Please provide an example of the event you want a Map created for. This can be found by pasting the contents of the Payload cell from EvtxECmd's CSV output. Ideally, double-click on the Payload cell of interest and use the Format button in Timeline Explorer before pasting here.
      render: xml
      placeholder: |
        {
          EventData:
          {
            Data:
            [
              {
                @Name: ServiceName,
                #text: Microsoft Office Click-to-Run Service
              },
              {
                @Name: ImagePath,
                #text: """C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe"" /service"
              },
              {
                @Name: ServiceType,
                #text: user mode service
              },
              {
                @Name: StartType,
                #text: auto start
              },
              {
                @Name: AccountName,
                #text: LocalSystem
              }
            ]
          }
        }
    validations:
      required: false
  - type: textarea
    id: event-context
    attributes:
      label: Event Context
      description: Tell us why this particular event deserves to be mapped in EvtxECmd.
      placeholder: How has this event helped in your investigation? What does this event tell the examiner?
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Is there anything else we need to know?
    validations:

      required: false


